const PHRASES = [
    "No",
    "Are you sure?",
    "Like... really sure? 😥",
    "Surely that was a mistake lol",
    "You silly! 😆",
    "Como vc é boba 🤡",
    "Don't do this to me 🥺",
    "I'm gonna cry... 😢",
    "Bubu, you're breaking my heart",
    "Do you not like Giraffon?",
    "BE MY VALENTINE GAWD D*MMIT 😠",
    "Just click 'Yes'",
    "You're being ridiculous",
    "Vou peidar na sua cara 😣💨🤢",
    "There is no other option",
    "This is not a democracy",
    "You are MINE!!!",
    "Rage is over",
    "I'm sorry 😔",
    "Keep being 괜찮아",
    "Even though life is 시발새끼야!",
    "I see you through the camera 👀",
    "You're laughing 😂",
    "I'll accept it as a 'YES'",
    "Hmmm! (pinching your butt) 🫣",
    "진짜 너무 예뻐요! 😍",
    "내 발렌타인이 되어줘, 공주님"
]

export default PHRASES;